#!/bin/bash
#set -e 

dummy_port=$1; binfile=$2; dummy_port_fullpath="/dev/$1"
echo "${dummy_port} ${binfile} ${dummy_port_fullpath}"

# Get the directory where the script is running.
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#  ----------------- IMPORTANT -----------------
# The 2nd parameter to upload-reset is the delay after resetting before it exits
# This value is in milliseonds
# You may need to tune this to your system
# 750ms to 1500ms seems to work on my Mac
${DIR}/upload-reset ${dummy_port_fullpath} 1000

${DIR} ${dummy_port_fullpath} 1000
sleep 5
echo "Issuing the DFU Command"

DFU_UTIL=${DIR}/dfu-util

${DFU_UTIL} -d 0x1209 0xEE03 -D ${binfile}
echo "Done flashing"
